# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cubelist',
            fields=[
                ('card_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=150)),
                ('card_cost', models.SmallIntegerField(blank=True, null=True)),
                ('card_image', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cubeList',
                'managed': True,
            },
        ),
    ]
